spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/item
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  profiles:
    active: local

logging.level:
    org.hibernate.SQL: debug
